apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-map-example
  labels:
    env1: prod
    env2: test
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
       containers:
        - name: env-demo
          image: nginx
          envFrom:
            - configMapRef:
                 name: game-demo
 
