apiVersion: v1
kind: Pod
metadata: 
   name: kucc8
spec: 
     containers:
     # container 1
      - name: nginx
        image: nginx:latest
        ports:   
         - containerPort: 8080
     # continer 2
      - name: consul
        image: consul:1.15.4
        ports:
           - containerPort: 9246

