apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pods
spec:
  containers:
  #Container 01
  - name: web
    image: httpd
    ports:
    - containerPort: 80
  #Container 02
  - name: rexdis
    image: redis
