apiVersion: v1
kind: PersistentVolume
metadata:
   name: mysql-persistantvolume
   labels:
      app: mysql
spec:
   accessModes:
            - ReadWriteMany
   capacity:
           storage: 6Gi
   nfs:
        server: 172.31.15.255
        path: "/mnt/newdata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
   name: mysql-pvc
   labels: 
      app: mysql
spec:
   accessModes:
             - ReadWriteMany
   resources:
         requests:
             storage: 4Gi
