apiVersion: v1
kind: ConfigMap
metadata:
    name: mysql-cm
    namespace: project1
data:
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress_user
#    MYSQL_USER: root

---
apiVersion: v1
kind: Secret
metadata: 
    name: mysql-pass
    namespace: project1
type: opaque
data: 
   password: cGFzc3dyZA==
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: mysql-persistantvolume
   namespace: project1
   labels:
      app: mysql
spec:
   accessModes:
            - ReadWriteOnce
   capacity:
           storage: 6Gi
   nfs:
        server: 172.31.4.120
        path: "/mnt/dbdata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
   name: mysql-pvc
   namespace: project1
   labels: 
      app: mysql
spec:
   accessModes:
             - ReadWriteOnce
   resources:
         requests:
             storage: 6Gi
---
apiVersion: v1
kind: Service
metadata:
    name: wordpress-service
    namespace: project1
    labels:
        app: mysql
spec:
    type: ClusterIP
    ports:
       - port: 3306
         targetPort: 3306
    selector:
       app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: project1
  labels:
    app: mysql
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: mysql
  template:
    metadata: 
      labels:
        app: mysql
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mysql
            topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env: 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          envFrom:
            - configMapRef:
                name: mysql-cm                   
          volumeMounts:
            - name: mysql-pv
              mountPath: "/var/lib/mysql"
