apiVersion: v1
kind: Pod
metadata:
  name: multi-cont-pod

spec:
  containers:
  # container 1
   - name: alpha
     image: nginx
     env: 
      - name: alpha
        value: "this is alpha container" 
  # ccontainer 2
   - name: beta
     image: busybox
     command: ["sh", "-c", "sleep 4800"]
     env: 
       - name: beta
         value: "this is brta container"


   
