apiVersion: v1
kind: Service
metadata: 
    name: master
    labels:
       app: svcmaster
       role: master
spec:
  ports:
    - port: 6379
      targetPort: 80
  selector: 
      app: redismaster
      role: master
---
apiVersion: apps/v1
kind: Deployment
metadata: 
   name: master
   labels:
    app: redismaster
    role: master
spec:
  selector:
   matchLabels:
     app: redismaster
     role: master
  replicas: 1
  template:
      metadata:
        labels:
         app: redismaster
         role: master
      spec:
       containers:
        - name: redis
          image: redis
          resources:
            requests:
             cpu: 100m
             memory: 100Mi
          ports:
           - containerPort: 6379
---

apiVersion: v1
kind: Service
metadata:
  name: slave
  labels:
    app: svcslave
    role: slave
spec:
   ports:
    - port: 6379
   selector:
      app: redisslave
      role: slave
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave
  labels: 
      app: redisslave
      role: slave
spec:
   selector:
    matchLabels:
     app: redisslave
     role: slave
   replicas: 1
   template:
    metadata:
      labels: 
       app: redisslave
       role: slave
    spec:
     containers:
      - name: redisslave01
        image: gcr.io/google_samples/gb-redisslave:v1
        ports:
         - containerPort: 6379
---

apiVersion: v1
kind: Service
metadata: 
  name: frontendsvc
  labels:
   app: sample
   tier: frontend
spec:
 type: NodePort
 ports:
  - port: 80
 selector:
    app: kubesample
    tier: frontend
---

apiVersion: apps/v1
kind: Deployment
metadata:
   name: frontend
   labels:
    app: kubesample
    tier: frontend
spec:
  selector:
   matchLabels:
     app: kubesample
     tier: frontend
  replicas: 2
  template:
   metadata:
    labels:
      app: kubesample
      tier: frontend
   spec:
    containers:
     - name: php-redis
       image: corelab/gb-frontend:v4
       resources:
        requests:
         cpu: 100m
         memory: 100Mi
       ports:
        - containerPort: 80
       env:
        - name: GET_HOSTS_FROM
          value: dns


